---
- hosts: "{{ application_name }}"
  vars:
    ansible_user: dev
    become: true
    #become_user: root
  gather_facts: yes
  roles:
    - { role: artemis, tags: ["never", "artemis"] }
    - { role: openliberty, tags: ["never", "openliberty"] }
      #- { role: redis-cluster, tags: ["never", "redis-cluster"] }
    - { role: redis-sentinel, tags: ["never", "redis-sentinel"] }
    - { role: java, tags: ["never", "java"] }
    - { role: java-alternatives, tags: ["never", "java-alternatives"] }

