---
galaxy_info:
  author: Abhishek Dubey
  description: Ansible role to setup a production grade redis cluster/server
  company: OpsTree Solutions

  license: MIT

  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags: ["redis", "ansible", "opstree"]
