---
- name: "Configure {{ _openliberty.name }} server.xml"
  template:
    src: "artemis/etc/openliberty.xml"
    dest: "{{ _openliberty.path }}/{{ _openliberty.name }}/etc/openliberty.xml"
  notify: "restart openliberty"