---
- name: "Init server with default values."
  set_fact:
    _server:
      openliberty_home: "{{ server.openliberty_home | default(openliberty_home_symlink) }}"
      name: "{{ server.name }}"
#      path: "{{ server.path }}"
#      host: "{{ server.host | default(openliberty_host) }}"
#      web_port: "{{ server.web_port | default(openliberty_web_port) }}"
#      web_host: "{{ server.web_host | default(openliberty_web_host) }}"
#      log_file: "{{ server.log_file | default(openliberty_log_file) }}"

- name: "Check if {{ _server.name }} already created"
  stat: path={{ _server.path }}/{{ _server.name }}
  register: server_path

- name: "Create server {{ _server.name }}"
  openliberty_create:
    name: "{{ _server.name }}"
#    path: "{{ _server.path }}"
  when: not server_path.stat.exists

#- name: "Update owner / group for server folder"
#  file:
#    path: "{{ _server.path }}/{{ _server.name }}"
#    state: directory
#    recurse: true
#    owner: "{{ openliberty_user.name }}"
#    group: "{{ openliberty_user.group }}"

- name: "Configure instance"
  include: configure.yml

#- name: "Install Openliberty server as service"
#  include_tasks: service.yml
