---
- name: "Init server with default values."
  set_fact:
    _server:
      openliberty_home: "{{ server.openliberty_home | default(openliberty_home_symlink) }}"
      name: "{{ server.name }}"
      path: "{{ server.path }}"
      user: "{{ server.user }}"
      password: "{{ server.password }}"
      host: "{{ server.host | default(artemis_host) }}"
      web_port: "{{ server.web_port | default(artemis_web_port) }}"
      web_host: "{{ server.web_host | default(artemis_web_host) }}"
      jolokia_cors: "{{ server.jolokia_cors | default(jolokia_cors) }}"
      log_file: "{{ server.log_file | default(artemis_log_file) }}"

- name: "Check if {{ _server.name }} already created"
  stat: path={{ _server.path }}/{{ _server.name }}
  register: server_path

- name: "Create server {{ _server.name }}"
  artemis_create:
    name: "{{ _server.name }}"
    path: "{{ _server.path }}"
    user: "{{ _server.user }}"
    password: "{{ _server.password }}"
  when: not server_path.stat.exists

- name: "Update owner / group for server folder"
  file:
    path: "{{ _server.path }}/{{ _server.name }}"
    state: directory
    recurse: true
    owner: "{{ artemis_user.name }}"
    group: "{{ artemis_user.group }}"

- name: "Configure instance"
  include: configure.yml

- name: "Install Openliberty server as service"
  include_tasks: service.yml
