---
- name: "Init service var with default values."
  set_fact:
    _service:
      name: "{{ _server.name }}"
      user: "{{ artemis_user.name }}"
      group: "{{ artemis_user.group }}"
      start: "{{ _server.path }}/{{ _server.name }}/bin/{{ _server.name }} start"
      stop: "{{ _server.path }}/{{ _server.name }}/bin/{{ _server.name }} stop"

- name: "Install {{ _service.name }} as service"
  template:
    src: "etc/systemd/openliberty.service"
    dest: "/etc/systemd/system/{{ _service.name }}.service"
    owner: "{{ _service.user }}"
    group: "{{ _service.group }}"

- name: "Enable service"
  service:
    name: "{{ _service.name }}"
    enabled: yes
  notify: "restart server"
