---
- name: "Add openliberty group"
  group:
    name: "{{ openliberty_user.group }}"
    state: "present"
    system: yes

- name: "Add openliberty user"
  user:
    name: "{{ openliberty_user.name }}"
    group: "{{ openliberty_user.group }}"
    createhome: no
    state: "present"
    system: yes

- name: "Create requires directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ openliberty_user.name }}"
    group: "{{ openliberty_user.group }}"
  with_items:
    - "{{ openliberty_home }}"
    - "{{ openliberty_log_dir }}"

- name: "Download and extract archive"
  unarchive:
    src: "{{ openliberty_download_url }}"
    dest: "{{ openliberty_install_dir }}"
    remote_src: yes
    owner: "{{ openliberty_user.name }}"
    group: "{{ openliberty_user.group }}"
    creates: "{{ openliberty_home }}/bin/openliberty"

- name: "Create link"
  file:
    src: "{{ openliberty_home }}"
    dest: "{{ openliberty_home_symlink }}"
    state: link
    owner: "{{ openliberty_user.name }}"
    group: "{{ openliberty_user.group }}"

- name: "Create servers"
  include_tasks: instance/instance.yml
  with_items: "{{ openliberty_servers }}"
  loop_control:
    loop_var: server

