---
# defaults file for openliberty

openliberty_version: "22.0.0.8"
openliberty_download_url: "https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/{{ openliberty_version }}/openliberty-{{ openliberty_version }}.zip"

openliberty_group:
  name: "openliberty"
  system: yes

openliberty_user:
  name: "openliberty"
  group: "{{ openliberty_group.name }}"
  createhome: no
  system: yes

openliberty_install_dir: "/opt"
openliberty_log_dir: []
openliberty_home: "{{ openliberty_install_dir }}/openliberty-{{ openliberty_version }}"
openliberty_home_symlink: "{{ openliberty_install_dir }}/openliberty"

openliberty_servers:
  - name: "test-profile"
    path: "{{ openliberty_home_symlink }}/usr"
    user: "admin"
    password: "C3t3l3ml1b3rty"

openliberty_host: "0.0.0.0"
openliberty_web_port: 8161
openliberty_web_host: localhost

#openliberty_port_openliberty: 61616
#openliberty_port_amqp: 5672
#openliberty_port_stomp: 61613
#openliberty_port_hornetq: 5445
#openliberty_port_mqtt: 1883

openliberty_log_file: "${openliberty.instance}/log/openliberty.log"
