---
# vars file for packages

# Detected OS
my_os: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}"

# Repos create
openliberty_repos_create: "{{ _openliberty_repos_create['all']
  | union ( _openliberty_repos_create[my_os]
  | default([]) ) }}"

# Repos download
openliberty_repos_download: "{{ _openliberty_repos_download['all']
  | union ( _openliberty_repos_download[my_os]
  | default([]) ) }}"

# Templates Copy
openliberty_templates_copy: "{{ _openliberty_templates_copy['all']
  | union ( _openliberty_templates_copy[my_os]
  | default([]) ) }}"

# Services Enable
openliberty_services_enable: "{{ _openliberty_services_enable['all']
  | union ( _openliberty_services_enable[my_os]
  | default([]) ) }}"

# SELinux Enable
openliberty_selinux_enable: "{{ _openliberty_selinux_enable['all']
  | union ( _openliberty_selinux_enable[my_os]
  | default([]) ) }}"

# Packages lists
openliberty_packages_remove: "{{ _openliberty_packages_remove['all']
  | union ( _openliberty_packages_remove[my_os]
  | default([]) ) }}"
openliberty_packages_repos: "{{ _openliberty_packages_repos['all']
  | union ( _openliberty_packages_repos[my_os]
  | default([]) ) }}"
openliberty_packages_prereq: "{{ _openliberty_packages_prereq['all']
  | union ( _openliberty_packages_prereq[my_os]
  | default([]) ) }}"
openliberty_packages_install: "{{ _openliberty_packages_install['all']
  | union ( _openliberty_packages_install[my_os]
  | default([]) ) }}"
